import React from 'react'
import Link from 'next/link';

export const metadata = {
  title: "Cousres",
  description: "Generated by create next app",
};
function page() {
  return (
    <div>
        <h3>
          Chose the Course which you want
        </h3>
        <ol>
          <li>
            <Link href={`courses/${"java"}`}>Click for java course</Link>
          </li>
          <li>
            <Link href={`courses/${"python"}`}>Click for Python Cousre </Link>
          </li>
          <li>
            <Link href={`courses/${"mern"}`}>Click for Mern Cousre </Link>
          </li>
          <li>
            <Link href={`/courses/${"sda"}`}>Click for SDA Cousre </Link>
          </li>
          <li>
            <Link href={`/courses/fetch`}>Click for Client Data Fetching </Link>
          </li>
          <li>
            <Link href={`/courses/server`}>Click for Server Data fetching </Link>
          </li>
        </ol>
    </div>
  )
}

export default page