import React from 'react'
export const metadata = {
  title: "Course of Java",
  description: "Generated by create next app",
};
function page() {
  return (
    <div>
        <h4>Wellcome to Java Page</h4>
        <button><a href="/courses">Back</a></button>
    </div>
  )
}

export default page